### ISSUE TITLE
Cannot export data with Chinese signs

### ISSUE THREAD

**Issue by datasert** [datasert/realfire#1]
I've tried export data in many ways after doing select request, but it always shows in files data with question marks instead proper Chinese signs. Any suggestion why something like this happens and how to overcome this?

**Comment by brsanthu** [comment]
Issue is resolved in Rebranded version of Realforce.

![image](https://user-images.githubusercontent.com/842964/29951337-e757fbfe-8e76-11e7-8fb9-03c0a536fc70.png)
