### ISSUE TITLE
Add full parent field name when dragging a field

### ISSUE THREAD

**Issue by datasert** [datasert/realfire#12]
Related to this, when dragging a field from the Parent fields, put in the full path instead of just the field (ex: field3__r.Name instead of just Name).

**Comment by brsanthu** [comment]
In rebranded version of Realforce, query builder allows to search and build list of fields in a very flexible way. For ex., you can search for all parent fields upto 5 levels (be careful, if you have lots of parent references, this can take a while to index).

![http://i.imgur.com/bgvTqq6.gif](http://i.imgur.com/bgvTqq6.gif)
