### ISSUE TITLE
Internet connection unavailable

### ISSUE THREAD

**Issue by victorveg** [datasert/realfire#16]
After open application I'm getting this message:

Looks like internet connection is not available.

Datasert needsinternet connection to interact with Salesforce org. Please check the connection and try again.

And that's it, I cannot use the application.

**Comment by brsanthu** [comment]
hi, this is because application is not able to connect to internet. Are you behind the proxy?

**Comment by victorveg** [comment]
Yes, bit I can connect thru chrome, any particular site that I need to
access?

**Comment by brsanthu** [comment]
@victorveg Can you please ping me at support@datasert.com? We have updated to next version with some changes in proxy configuration. I think that would solve your problem. I can send you link to pre-release version so you can confirm if all is working.

**Comment by mengwei321** [comment]
I got the same error message.

**Comment by brsanthu** [comment]
@mengwei321 will you be able to try out a version with this issue fixed? If so please ping me at support@datasert.com

**Comment by brsanthu** [comment]
@victorveg @mengwei321 Version 2.0.27 released which has enhanced proxy detection. Please download from https://www.datasert.com/products/realforce. I worked with another custom who had same issue and they are fine with 2.0.27.

I will wait for your response for another 2 days and then close this issue. 

Thank you both for reporting the issue and bringing it to our attention.
