### ISSUE TITLE
SOQL query not returning fields listed

### ISSUE THREAD

**Issue by jamesloughney** [datasert/realfire#18]
Using the Query Editor when I type in:
select groupid, group.developername from groupmember
I was expecting to see the developername field listed but it does not appear:

![image](https://user-images.githubusercontent.com/3610332/33784952-c1cb2354-dc17-11e7-9fe6-a43e3a35cf7b.png)

**Comment by brsanthu** [comment]
Will take a look and update.

**Comment by brsanthu** [comment]
Confirming that it is an issue. Will work on a fix and include in the next version, 3.5. Next version is due in about two weeks.

If you would like a patch, we can work on it. Pease let us know.

**Comment by brsanthu** [comment]
The issue has been fixed and released as part of 4.0.1
