### ISSUE TITLE
Horizontal scrollbar button is hiding when the window is not maximized

### ISSUE THREAD

**Issue by modliszka** [datasert/realfire#21]
As in topic: horizontal scrollbar button is hiding when the window of the program is not maximized. I'm talking about the scrollbar in this window which appears when I click Object -> Preview data.

**Comment by datasert** [comment]
@modliszka thank you for reporting the issue. Can you please give more details about the version of the product you are using? 

May be you can send us a inproduct message, which will automatically include the product version? (You can get to it from Help -> Contact Support).

**Comment by brsanthu** [comment]
Issue is partially addressed in Realfire 5.0.0. The reason why it wasn't fully fixed is min width for that window is driven by toolbar size and since toolbar has many actions and status text, it cannot removed we shorten the toolbar width, which we will look into next version
