### ISSUE TITLE
Open File folder location

### ISSUE THREAD

**Issue by billmacuk** [datasert/realfire#23]
would be nice if Open File dialog box opened up to same location as Save As...

**Comment by datasert** [comment]
@billmacuk Do you mean, every time Open file dialog opens, it should defaults to previously opened location?

**Comment by billmacuk** [comment]
Hi there

Thanks for your reply.

No I meant it should default to “C:\Users\<User>\.realfire\rfcommon\files”

That is where the Save As dialog default to (or so it appears to me).

So it makes sense (to me) that the user will want to Open a file from the place they Saved it to.

b


Sent from Mail for Windows 10

**Comment by datasert** [comment]
That place is meant to store only editor files that product creates and not meant for customer to store their files. Customers should store their files (for ex., csv or other files) that they create, outside of realfire workspace.

With that said, will provide preferences where use can choose a particular folder so they can choose this folder. If not, will default to previously opened folder so it would serve the intent.

I will let you know if we can include in next version (planned to be 5.0)

**Comment by billmacuk** [comment]
Hi there

Thanks for your reply.

The “editor files” that the product creates are my files. They are how I use the product.  I create useful scripts and test apex code and having these files there is part of my admin processing to my instances

Anyway, your solution sounds fine

Thanks,

bill



Sent from Mail for Windows 10

**Comment by datasert** [comment]
Yes :) didn't mean to say, customer don't own those files but meant to say, product created and has an understanding of what those files are vs customer created outside of the product.

If you have Ess+ edition, the files stores in the rfcommon/files are listed in the "Editor Files" view.

**Comment by billmacuk** [comment]
😊

Sent from Mail for Windows 10

**Comment by brsanthu** [comment]
Issue is fixed in V5.0.0 of Realfire.
