### ISSUE TITLE
Essentials has the same features as free

### ISSUE THREAD

**Issue by moguejiofor** [datasert/realfire#25]
I have been using this tool for a little bit now and finally paid for an upgraded version. There is no difference form free and essential. I want to know the difference or get a refund.

**Comment by datasert** [comment]
@moguejiofor Essentials doesn't have same features as Free. The features among different editions are listed at https://www.datasert.com/products/realfire/pricing.

We will reach out to you over email so we can resolve it ensure essentials is setup or refund the charge if you are not still satisfied.

Btw, can you please send a inproduct request? (Help Menu -> Contact Support)
