### ISSUE TITLE
SQL Builder is not showing Custom Object field additions

### ISSUE THREAD

**Issue by towen-procore** [datasert/realfire#28]
FYI for next release, if possible....Build Soql UI does not show new fields added to Custom Object, even after 'Refresh Object Details'. The Object browser 'Fields' tab **does** show the new fields but the query builder **does not**. I have to delete/re-create the connection to get the fields to show up in build soql UI. While delete/re-create connection is not a 'real' burden, it is a pain point--when working a new project where scrums produce frequent new fields for new feature. Using Essential 5.2.3.

**Comment by brsanthu** [comment]
Version 5.3.0 (which should be released in next few days) will have button to Refresh fields in build soql dialog.

![image](https://user-images.githubusercontent.com/842964/130848135-b85692a9-44c9-429c-a9df-49e6b05427de.png)
