### ISSUE TITLE
Issue accessing Salesforce SOQL Data - running on Proxy Settings

### ISSUE THREAD

**Issue by datasert** [datasert/realfire#3]
Anonymous created an issue 2014-03-26
I have installed the application and it seems to be fine, but the problem is that I get an error when I run the SOQL in any object (access to the Instance is denied) I can see the objects, the fields and pretty much everything in all SFDC instances, but I cannot get the SOQL to work.
I am using the Network Manual Proxy settings and like I said I was able to access all dev instances no problem it is just that I cannot get access to get the data.
By any chance you have any idea what setting I can change in SFDC or what I should look for.? Your help would be highly appreciated,
Thanks

Yes, this is very big problem for me too. If you can, please fix it, because now all SOQL queries we must execute in Developer Console.

Still an issue unfortunatelly . Can it be that the SoQlScrapbook soql query not using the manual proxy ? Only the Explorer Object review works fine. Fire an soql give Error Executing Query: Connection to https://xxxxx.my.salesforce.com refused.

**Comment by brsanthu** [comment]
Proxy feature is reworked in new version
