### ISSUE TITLE
 using datetime in soql select statements

### ISSUE THREAD

**Issue by datasert** [datasert/realfire#8]
I can run this command in orher tools (Cloudingo Studio and FuseIT) but in Real Force it prompts me for values thinking the colons : in the datetime value are variables. I have tried making the value a variable with no success. Below is an example of a query that doesnt seem to work for me:
SELECT Id, Name, RecordTypeid, CreatedDate FROM Account WHERE LastModifiedDate > 2015-04-06T21:40:32

**Comment by brsanthu** [comment]
Latest version supports turning off the bind variables. If you do that, query is passed to sfdc as is.

**Comment by datasert** [comment]
If you turn off the bind variable detection, then soql should run fine. Btw, to run your exact query, you need to append `Z` to indicate the timezone. So this query runs fine in latest version. 

`SELECT Id, Name, RecordTypeid, CreatedDate FROM Account WHERE LastModifiedDate > 2015-04-06T21:40:32Z`
